apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: 2017-07-14T14:38:59Z
  generation: 1
  labels:
    k8s-app: fluentd-logging
    kubernetes.io/cluster-service: "true"
    version: v1
  name: fluentd
  namespace: kube-system
  resourceVersion: "13482588"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/daemonsets/fluentd
  uid: 2c255bca-68a2-11e7-8527-fa163eecdaa1
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      kubernetes.io/cluster-service: "true"
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: fluentd-logging
        kubernetes.io/cluster-service: "true"
        version: v1
    spec:
      containers:
      - image: antonh/fluentd-kubernetes-daemonset
        imagePullPolicy: Always
        name: fluentd
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
  templateGeneration: 1
  updateStrategy:
    type: OnDelete
status:
  currentNumberScheduled: 11
  desiredNumberScheduled: 11
  numberAvailable: 10
  numberMisscheduled: 0
  numberReady: 10
  numberUnavailable: 1
  observedGeneration: 1
  updatedNumberScheduled: 11
